### ISSUE TITLE
Roblox plugin prints to output excessively

### ISSUE THREAD

**Issue by Sjdinsd** [JohnnyMorganz/luau-lsp#1127]
When doing changing anything in studio, it updates the datamodel info. This is great, I'm glad its able to detect these things, but can we add an option in the LuauLSP settings to disable printing everything to the output?
![Image](https://github.com/user-attachments/assets/42ec51e3-fa4b-455e-b199-5c4881db9130)

Something like this could be beneficial.
![Image](https://github.com/user-attachments/assets/817cfd5b-6d0e-4294-adbf-33f077ccc763)

**Comment by Barocena** [comment]
are you using latest version of plugin ? this was fixed couple years ago

**Comment by Sjdinsd** [comment]
I should be, I am using this and are still experiencing these excessive messages: [https://create.roblox.com/store/asset/10913122509/Luau-Language-Server-Companion](https://create.roblox.com/store/asset/10913122509/Luau-Language-Server-Companion)

**Comment by JohnnyMorganz** [comment]
The plugin has been refactored quite a bit. There is a `logLevel` option in settings as well.
I am going to assume this is no longer an issue, but feel free to reopen if you still experience this.
