### ISSUE TITLE
Luau-lsp incorrectly shows hidden variadic anys in autocomplete

### ISSUE THREAD

**Issue by skanosue** [JohnnyMorganz/luau-lsp#1229]
This pops up as a consequence of an implementation detail of the new type solver, where all user defined functions have variadic any tails on the argument packs. These are tagged as hidden, and UX would probably be improved by hiding them in autocomplete.

<img width="341" height="52" alt="Image" src="https://github.com/user-attachments/assets/f6a498c3-6908-4aa4-abc9-5c0c4d48726f" />

**Comment by JohnnyMorganz** [comment]
Relevant code is https://github.com/JohnnyMorganz/luau-lsp/blob/b4bdb6d52281f1b6bf4cd9bf4c92a03843871ae4/src/operations/Completion.cpp#L394 and we should change it to match https://github.com/luau-lang/luau/blob/6169fa15d85c766c108c90eb68289021b5eee705/Analysis/src/ToString.cpp#L1192

**Comment by JohnnyMorganz** [comment]
Fixed in https://github.com/JohnnyMorganz/luau-lsp/commit/45babd209463dc217e9ab2c5cbf6847b4869aba2

**Comment by abidbmt** [comment]
This is still an issue when using `typeof()` as shown in this picture:

<img width="874" height="210" alt="Image" src="https://github.com/user-attachments/assets/19809c7e-57cc-434d-b224-71f50ef9436a" />
