### ISSUE TITLE
React Spring package breaks the lsp intellisence

### ISSUE THREAD

**Issue by krungkualalumpur** [JohnnyMorganz/luau-lsp#919]
https://wally.run/package/chriscerie/roact-spring?version=2.0.0

After installing the mentioned package, the intellisence and luau-lsp live functionalities are broken.

**Comment by JohnnyMorganz** [comment]
You immediately closed this issue - is it a problem or it was resolved?

**Comment by krungkualalumpur** [comment]
Hey, sorry for the very late reply, I figured I should post this issue for the ReactSpring package instead of this. However the issue is still not resolved. Apologies!
